#!/bin/bash
#
#################
# BUILD QUDA
#################

ENV_SCRIPT=env.Intel2019_0.1.144.sh
source ./${ENV_SCRIPT}

PKG_SRC=${QUDA_SRC}
PKG_INSTALL=${QUDA_INSTALL}
PKG_DIST=${QUDA_DIST}

BUILD_TAG=${ENV_PRECISION}-prec


if [ -d ${PKG_INSTALL} ]; 
then 
  rm -rf ${PKG_INSTALL}
fi
mkdir -p ${PKG_INSTALL}
pushd ${PKG_INSTALL}


${PK_CMAKE}  \
	-G "Eclipse CDT4 - Unix Makefiles" \
	-DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE \
	-DCMAKE_ECLIPSE_MAKE_ARGUMENTS=-j8 \
	-DCMAKE_ECLIPSE_VERSION="4.7.2" \
	-DQUDA_DIRAC_CLOVER=ON \
	-QUDA_DIRAC_CLOVER_HASENBUSCH=ON \
	-DQUDA_DIRAC_DOMAIN_WALL=ON \
	-DQUDA_DIRAC_NDEG_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_STAGGERED=OFF \
	-DQUDA_DIRAC_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_TWISTED_CLOVER=OFF \
	-DQUDA_DIRAC_WILSON=ON \
	-DQUDA_DYNAMIC_CLOVER=OFF \
	-DQUDA_FORCE_GAUGE=OFF \
	-DQUDA_FORCE_HISQ=OFF \
	-DQUDA_GAUGE_ALG=OFF \
	-DQUDA_GAUGE_TOOLS=OFF \
	-DQUDA_GPU_ARCH=${SM} \
	-DQUDA_GPU_DIRECT=ON \
	-DQUDA_QDPJIT=OFF \
	-DQUDA_INTERFACE_QDPJIT=OFF \
	-DQUDA_INTERFACE_MILC=OFF \
	-DQUDA_INTERFACE_CPS=OFF \
	-DQUDA_INTERFACE_QDP=ON \
	-DQUDA_INTERFACE_TIFR=OFF \
	-DQUDA_MAGMA=OFF	\
	-DQUDA_QMP=ON \
        -DMPIEXEC_NUMPROC_FLAG="-n" \
        -DMPIEXEC_MAX_NUMPROCS=8 \
        -DQUDA_QMPHOME=${QMP_INSTALL} \
	-DQUDA_OPENMP=ON \
	-DQUDA_MULTIGRID=ON \
	-DQUDA_MAX_MULTI_BLAS_N=9 \
        -DQUDA_DOWNLOAD_EIGEN=NO \
        -DEIGEN_INCLUDE_DIR=${EIGEN_SRC} \
	-DCMAKE_INSTALL_PREFIX=${PKG_INSTALL} \
	-DCMAKE_BUILD_TYPE=DEVEL \
        -DCMAKE_CXX_COMPILER=${PK_CXX} \
        -DCMAKE_C_COMPILER=${PK_CC} \
	-DCMAKE_EXE_LINKER_FLAGS="${OMPFLAGS} -L${PK_CUDA_HOME}/lib64 -L${PK_CUDA_HOME}/nvvm/lib64 -lcublas" \
	-DQUDA_BUILD_SHAREDLIB=NO \
	-DQUDA_BUILD_ALL_TESTS=OFF \
	${PKG_SRC}

#        -DMPIEXEC_EXECUTABLE="/usr/local/mvapich2-2.3/bin/mpirun" \


${MAKE} VERBOSE=1
${MAKE} install

popd
popd
