#!/bin/bash
#
#################
# BUILD QUDA
#################

ENV_SCRIPT=env.GCC_8.4.0_SpectrumMPI.sh
source ./${ENV_SCRIPT}

PKG_SRC=${QUDA_SRC}
PKG_INSTALL=${QUDA_INSTALL}
PKG_DIST=${QUDA_DIST}

BUILD_TAG=${ENV_PRECISION}-prec
QDPJIT_QUDA=${QDPJIT_INSTALL}/${BUILD_TAG}

# pushd ${BUILDDIR}

# BUILD_FILES_DIST=build_${PKG_DIST}

# if [ -d ${BUILD_FILES_DIST} ]; 
# then 
#   rm -vrf ${BUILD_FILES_DIST}
# fi

# mkdir -v ${BUILD_FILES_DIST}
# cd ${BUILD_FILES_DIST}


if [ -d ${PKG_INSTALL} ]; 
then 
  rm -rf ${PKG_INSTALL}
fi
mkdir -p ${PKG_INSTALL}
pushd ${PKG_INSTALL}


${PK_CMAKE}  \
	-DQUDA_DIRAC_CLOVER=ON \
	-DQUDA_DIRAC_DOMAIN_WALL=OFF \
	-DQUDA_DIRAC_NDEG_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_STAGGERED=OFF \
	-DQUDA_DIRAC_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_TWISTED_CLOVER=OFF \
	-DQUDA_DIRAC_WILSON=ON \
	-DQUDA_DYNAMIC_CLOVER=OFF \
	-DQUDA_FORCE_GAUGE=OFF \
	-DQUDA_FORCE_HISQ=OFF \
	-DQUDA_GAUGE_ALG=OFF \
	-DQUDA_GAUGE_TOOLS=OFF \
	-DQUDA_GPU_ARCH=${SM} \
	-DQUDA_INTERFACE_QDPJIT=ON \
	-DQUDA_QDPJIT=ON \
	-DQUDA_QDPJITHOME=${QDPJIT_QUDA} \
	-DQUDA_INTERFACE_MILC=OFF \
	-DQUDA_INTERFACE_CPS=OFF \
	-DQUDA_INTERFACE_QDP=ON \
	-DQUDA_INTERFACE_TIFR=OFF \
	-DQUDA_OPENMP=ON	\
	-DQUDA_MAGMA=OFF	\
	-DQUDA_QMP=ON \
	-DQUDA_QMPHOME=${QMP_INSTALL} \
        -DQUDA_QIO=ON \
        -DQUDA_QIOHOME=${QDPJIT_QUDA} \
        -DQUDA_LIMEHOME=${QDPJIT_QUDA} \
	-DQUDA_MULTIGRID=ON \
        -DQUDA_MAX_MULTI_BLAS_N=9 \
        -DQUDA_DOWNLOAD_EIGEN=NO \
        -DEIGEN_INCLUDE_DIR=${EIGEN_SRC} \
	-DCMAKE_INSTALL_PREFIX=${PKG_INSTALL} \
	-DCMAKE_BUILD_TYPE=DEVEL \
        -DCMAKE_CXX_COMPILER=${PK_CXX} \
        -DCMAKE_C_COMPILER=${PK_CC} \
        -DCMAKE_LINKER=${PK_CXX} \
	-DQUDA_BUILD_SHAREDLIB=NO \
	-DQUDA_BUILD_ALL_TESTS=OFF \
	-DCMAKE_EXE_LINKER_FLAGS="${JIT_LDFLAGS}" \
	${PKG_SRC}
    

${MAKE} VERBOSE=1
${MAKE} install

popd
popd
