#!/bin/bash
#
#################
# BUILD QUDA-NOJIT
#################

ENV_SCRIPT=env.GCC_8.4.0_SpectrumMPI.sh
source ./${ENV_SCRIPT}

PKG_SRC=${QUDA_SRC_GP4}
PKG_INSTALL=${QUDA_INSTALL_GP4}
PKG_DIST=${QUDA_DIST_GP4}

BUILD_TAG=${ENV_PRECISION}-prec

QDP_GP4_QUDA=${QDP_INSTALL_GP4}/${BUILD_TAG}

if [ -d ${PKG_INSTALL} ]; 
then 
  rm -rf ${PKG_INSTALL}
fi
mkdir -p ${PKG_INSTALL}
pushd ${PKG_INSTALL}


${PK_CMAKE}  \
	-DQUDA_DIRAC_CLOVER=ON \
	-DQUDA_DIRAC_DOMAIN_WALL=OFF \
	-DQUDA_DIRAC_NDEG_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_STAGGERED=OFF \
	-DQUDA_DIRAC_TWISTED_MASS=OFF \
	-DQUDA_DIRAC_TWISTED_CLOVER=OFF \
	-DQUDA_DIRAC_WILSON=ON \
	-DQUDA_DYNAMIC_CLOVER=OFF \
	-DQUDA_FORCE_GAUGE=OFF \
	-DQUDA_FORCE_HISQ=OFF \
	-DQUDA_GAUGE_ALG=OFF \
	-DQUDA_GAUGE_TOOLS=OFF \
	-DQUDA_GPU_ARCH=${SM} \
	-DQUDA_INTERFACE_MILC=OFF \
	-DQUDA_INTERFACE_CPS=OFF \
	-DQUDA_INTERFACE_QDP=ON \
	-DQUDA_INTERFACE_TIFR=OFF \
	-DQUDA_OPENMP=ON	\
	-DQUDA_MAGMA=OFF	\
	-DQUDA_QMP=ON \
	-DQUDA_QMPHOME=${QMP_INSTALL_GP4} \
        -DQUDA_QIO=ON \
        -DQUDA_QIOHOME=${QDP_GP4_QUDA} \
        -DQUDA_LIMEHOME=${QDP_GP4_QUDA} \
	-DQUDA_MULTIGRID=ON \
        -DQUDA_MAX_MULTI_BLAS_N=9 \
        -DQUDA_DOWNLOAD_EIGEN=NO \
        -DEIGEN_INCLUDE_DIR=${EIGEN_SRC_GP4} \
	-DCMAKE_INSTALL_PREFIX=${PKG_INSTALL} \
	-DCMAKE_BUILD_TYPE=DEVEL \
        -DCMAKE_CXX_COMPILER=${PK_CXX} \
        -DCMAKE_C_COMPILER=${PK_CC} \
        -DCMAKE_LINKER=${PK_CXX} \
	-DQUDA_BUILD_SHAREDLIB=NO \
	-DQUDA_BUILD_ALL_TESTS=OFF \
	-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS_GP4}" \
	${PKG_SRC}
    

${MAKE} VERBOSE=1
${MAKE} install

popd
popd
